# Lesson 5: Vacation planning using CSV files

# 第 5 课：使用 CSV 文件进行假期规划

In this lesson you'll learn to read in and work with data stored in CSV format. Data of this type looks like a table with rows and columns, and is referred to by programmers as **structured data**.

在本课程中，您将学习读入和使用以 CSV 格式存储的数据。这种类型的数据看起来像一个有行和列的表格，被程序员称为“结构化数据”。

As always, begin by loading the helper functions you'll use:

与往常一样，首先加载您将使用的辅助函数：

In [1]:
# Imports
import sys
import os
import importlib

parent_dir = os.path.dirname(os.getcwd())
if parent_dir not in sys.path:
    sys.path.insert(0, parent_dir)

import helper_functions
importlib.reload(helper_functions)
from helper_functions import get_llm_response, print_llm_response, display_table
from IPython.display import Markdown
import csv

Note that `import csv` here is new. Don't worry about the details for now, but this line of code will be used later to read in CSV data. You'll learn more about this code in Course 4.

请注意，此处的“导入 csv”是新的。现在不用担心细节，但这行代码稍后将用于读取 CSV 数据。您将在课程 4 中了解有关此代码的更多信息。

## Loading data from a CSV file

## 从 CSV 文件加载数据

You'll use the file ```itinerary.csv```, which has information about arrival and departure dates for each destination in a trip around the world.

您将使用文件“itinerary.csv”，其中包含有关环球旅行中每个目的地的到达和出发日期的信息。

Here is the code to load the file - the first part is the same as you've been using up to this point:

这是加载文件的代码 - 第一部分与您到目前为止使用的相同：

In [12]:
f = open("itinerary.csv", 'r')

The next part, where you read the data in from the file, is different because you are now reading in a CSV file:

下一部分是从文件中读取数据，该部分有所不同，因为您现在正在读取 CSV 文件：

In [ ]:
csv_reader = csv.DictReader(f)
itinerary = []
for row in csv_reader:
    print(row)
    itinerary.append(row)

{'Arrival': 'July-01', 'Departure': 'July-08', 'City': 'New York', 'Country': 'USA'}
{'Arrival': 'July-09', 'Departure': 'July-16', 'City': 'Rio de Janeiro', 'Country': 'Brazil'}
{'Arrival': 'July-17', 'Departure': 'July-24', 'City': 'Cape Town', 'Country': 'South Africa'}
{'Arrival': 'July-25', 'Departure': 'August-01', 'City': 'Istanbul', 'Country': 'Turkey'}
{'Arrival': 'August-02', 'Departure': 'August-09', 'City': 'Paris', 'Country': 'France'}
{'Arrival': 'August-10', 'Departure': 'August-17', 'City': 'Tokyo', 'Country': 'Japan'}
{'Arrival': 'August-18', 'Departure': 'August-25', 'City': 'Sydney', 'Country': 'Australia'}

Now close the file:

现在关闭文件：

In [14]:
f.close()

You can print the itinerary to view it's content and use the `type` function to check the datatype:

您可以打印行程以查看其内容并使用“type”函数检查数据类型：

In [15]:
print(itinerary)

[{'Arrival': 'July-01', 'Departure': 'July-08', 'City': 'New York', 'Country': 'USA'}, {'Arrival': 'July-09', 'Departure': 'July-16', 'City': 'Rio de Janeiro', 'Country': 'Brazil'}, {'Arrival': 'July-17', 'Departure': 'July-24', 'City': 'Cape Town', 'Country': 'South Africa'}, {'Arrival': 'July-25', 'Departure': 'August-01', 'City': 'Istanbul', 'Country': 'Turkey'}, {'Arrival': 'August-02', 'Departure': 'August-09', 'City': 'Paris', 'Country': 'France'}, {'Arrival': 'August-10', 'Departure': 'August-17', 'City': 'Tokyo', 'Country': 'Japan'}, {'Arrival': 'August-18', 'Departure': 'August-25', 'City': 'Sydney', 'Country': 'Australia'}]

In [16]:
type(itinerary)

list

Now take a look at the first item

现在看第一项
* Remember the first item in a list has index 0

* 记住列表中的第一项的索引为 0

In [17]:
# Print item 0 
print(itinerary[0])

{'Arrival': 'July-01', 'Departure': 'July-08', 'City': 'New York', 'Country': 'USA'}

This is a dictionary. You can access a particular value by passing in the key - let's look at the `Country` value in the first row of the itinerary:

这是一本字典。您可以通过传入键来访问特定值 - 让我们看看行程第一行中的“Country”值：

In [18]:
print(itinerary[0]["Country"])

USA

## Try for yourself!

## 亲自尝试一下！

Pause the video and explore other rows in the itinerary list, or individual items in any destination. Modify the code below to explore this world tour!

暂停视频并探索行程列表中的其他行，或任何目的地的单个项目。修改下面的代码来探索这个世界之旅吧！

In [19]:
print(itinerary[0])
print(itinerary[0]["Country"])

{'Arrival': 'July-01', 'Departure': 'July-08', 'City': 'New York', 'Country': 'USA'}
USA

<p style="background-color:#F5C780; padding:15px"> 🤖 <b>Use the Chatbot</b>:

<p style="background-color:#F5C780; padding:15px"> 🤖 <b>使用聊天机器人</b>：
    <br><br>
    Explain this code line by line:

逐行解释一下这段代码：
    <br><br>f = open("itinerary.csv", 'r')
    <br>csv_reader = csv.DictReader(f)
    <br>itinerary = []

<br>行程=[]
    <br>for row in csv_reader:

<br>对于 csv_reader 中的行：
    <br>itinerary.append(row)

<br>行程.append(行)
    <br><br>f.close()
</p>

## Structured Data

## 结构化数据

Let's visualize this itinerary in a more readable way.

让我们以更易读的方式可视化此行程。

* Use the ```display_table``` helper function:

* 使用“display_table”辅助函数：

In [20]:
display_table(itinerary)

Next, write code to filter the table based on some criterion - in this case if the country is Japan - and then add the information for that stop to a new list called `filtered_data`:

接下来，编写代码以根据某些条件过滤表（在本例中，如果该国家/地区是日本），然后将该站点的信息添加到名为“filtered_data”的新列表中：

In [21]:
# Create an empty list to store the filtered data
filtered_data = []

# Filter by country
for trip_stop in itinerary:
    # For example: get the destinations located in "Japan"
    if trip_stop["Country"] == "Japan":
        filtered_data.append(trip_stop)

In [22]:
display_table(filtered_data)

Note that the `filtered_data` variable only contains one row.

请注意，“filtered_data”变量仅包含一行。

## Using AI to suggest trip activities

## 使用人工智能建议旅行活动

Retrieve the first destination and then ask an LLM for suggestions of activities to do in that location during the dates of the visit:

检索第一个目的地，然后向法学硕士询问访问日期期间在该地点进行的活动的建议：

In [23]:
# Select the first destination from the itinerary list (Hint: index=0)
trip_stop = itinerary[0]
print(trip_stop)

{'Arrival': 'July-01', 'Departure': 'July-08', 'City': 'New York', 'Country': 'USA'}

Create variables to store all the individual items from ```trip_stop```:

创建变量来存储“trip_stop”中的所有单独项目：

In [24]:
city = trip_stop["City"]
country = trip_stop["Country"]
arrival = trip_stop["Arrival"]
departure = trip_stop["Departure"]

Write a prompt to get activity suggestions for your trip destination:

编写提示以获取您旅行目的地的活动建议：

In [25]:
prompt = f"""I will visit {city}, {country}, from {arrival} to {departure}. 
Please create a detailed daily itinerary."""

print(prompt)

I will visit New York, USA, from July-01 to July-08.
Please create a detailed daily itinerary.

Use Markdown to display the LLM response nicely in the Jupyter notebook:

使用 Markdown 在 Jupyter 笔记本中很好地显示 LLM 响应：

In [27]:
# Store the LLM response
response = get_llm_response(prompt)

# Print in Markdown format
display(Markdown(response))

Here's a concise, balanced 7-day NYC itinerary (July 1–8) optimized for summer weather, walkability, and iconic experiences—*without overpacking*:

**Key Notes**:
- Book *Statue of Liberty/Ellis Island ferry* and *9/11 Memorial Museum* tickets **in advance** (timed entry).
- Use MetroCard (subway/bus) or Uber/Lyft for longer distances.
- Pack light layers, comfortable shoes, sunscreen, and reusable water bottle (NYC has free refills).
- July is hot/humid—start early, hydrate, and use AC breaks (museums, cafes).

---

### **Day 1 (July 1): Arrival & Midtown Energy**
- **Afternoon**: Check in → Walk *Times Square* (neon buzz, people-watching).
- **Evening**: Dinner in *Theater District* (e.g., Joe Allen for classic NYC vibe) → Catch a Broadway show (*Wicked*, *Hamilton*, or discount TKTS booth tickets).

### **Day 2 (July 2): Icons & Skyline**
- **Morning**: *Statue of Liberty* (crown reservation essential) + *Ellis Island* (immigration history).
- **Afternoon**: Ferry to *Battery Park* → Walk *Stone Street* (cobblestone charm) → *Wall Street* + *Charging Bull*.
- **Evening**: Sunset at *One World Observatory* (book timed slot) → Dinner in *Tribeca*.

### **Day 3 (July 3): Culture & Green Space**
- **Morning**: *Metropolitan Museum of Art* (focus on Egyptian Wing + rooftop views; allow 3 hrs).
- **Afternoon**: *Central Park* (rent a bike or rowboat at Bethesda Terrace; stop at Bow Bridge, Strawberry Fields).
- **Evening**: Picnic dinner in the park → Jazz at *Dizzy’s Club* (Columbus Circle) or rooftop bar (*230 Fifth*).

### **Day 4 (July 4): Independence Day in NYC**
- **Day**: *Fireworks viewing* (best spots: Brooklyn Bridge Park, Roosevelt Island, or Upper West Side Hudson River piers). *Book dinner early*—restaurants fill fast.
- **Note**: Subways run all night; expect crowds. Arrive by 7 PM for prime views.

### **Day 5 (July 5): Neighborhood Immersion**
- **Morning**: *Greenwich Village* (Washington Square Park, historic brownstones, indie bookshops).
- **Afternoon**: *SoHo* (cast-iron architecture, art galleries, shopping on Prince St.).
- **Evening**: Dinner in *Chinatown* (Joe’s Shanghai for soup dumplings) → *Little Italy* stroll.

### **Day 6 (July 6): Art, Food & Views**
- **Morning**: *MoMA* (modern masterpieces; open at 10:30 AM).
- **Afternoon**: *High Line* (elevated park from Gansevoort St. to Hudson Yards) → *The Vessel* (photo op).
- **Evening**: Sunset drinks at *Westlight* (Williamsburg, Brooklyn) → Dinner in *DUMBO* (Juliana’s Pizza + Brooklyn Bridge walk back).

### **Day 7 (July 7): Local Life & Departure Prep**
- **Morning**: *Brooklyn Museum* (free first Saturday, but July 7 is Sunday—check pay-what-you-wish hours) → *Prospect Park* (lake, zoo, or farmers’ market).
- **Afternoon**: *Williamsburg* (street art, vintage shops, Smorgasburg food market if open) → Last-minute souvenirs (Museum of Modern Art Design Store or McNally Jackson Books).
- **Evening**: Farewell dinner in your favorite neighborhood.

### **Day 8 (July 8): Departure**
- Morning: Quick coffee at *Blue Bottle* (Flatiron) → Airport via AirTrain (JFK) or NJ Transit (EWR).

---

**Pro Tips**:
- **Food Musts**: Bagels (Ess-a-Bagel), pizza (Lombardi’s or Prince Street), halal cart (famous chicken & rice), black-and-white cookie.
- **Avoid**: Over-scheduling—NYC rewards spontaneity (e.g., stumbling upon a street performer in Washington Square).
- **Transport**: Subway is fastest. Avoid rush hour (8–10 AM, 5–7 PM) if possible.

Let me know if you’d like restaurant reservations, subway maps, or adjustments (e.g., kid-friendly, museum-deep dive, or budget focus). Enjoy NYC! 🗽

## Extra Practice

## 额外练习

In these exercises, you'll create an itinerary for another stop on the trip! 

在这些练习中，您将为旅途中的另一站创建行程！

### Exercise 1

### 练习 1

First, create a filtered dataset for Brazil. You'll need to update the `if` statement to select the right country. 

首先，为巴西创建一个过滤数据集。您需要更新“if”语句以选择正确的国家/地区。

In [28]:
# Create an empty list to store the filtered data
filtered_data = []

# Filter by country
for trip_stop in itinerary:
    # For example: get the destinations located in "Brazil"
    # Complete code on next line:
    if trip_stop["Country"] == "Brazil":
        filtered_data.append(trip_stop)

print(filtered_data)

[{'Arrival': 'July-09', 'Departure': 'July-16', 'City': 'Rio de Janeiro', 'Country': 'Brazil'}]

### Exercise 2

### 练习 2

Next, update the variables to pass in the prompt to the LLM. You'll need to modify the code on the next line to select the first item from `filtered_data` rather than the whole `itinerary`.

接下来，更新变量以将提示传递给 LLM。您需要修改下一行的代码以从“filtered_data”而不是整个“itinerary”中选择第一项。

In [30]:
trip_stop = filtered_data[0]

city = trip_stop["City"]
country = trip_stop["Country"]
arrival = trip_stop["Arrival"]
departure = trip_stop["Departure"]

print(f" The city is: {city}")
print(f" The country is: {country}")
print(" The arrival date is: {arrival}")
print(" The departure date is: {departure}")

 The city is: Rio de Janeiro
 The country is: Brazil
 The arrival date is: {arrival}
 The departure date is: {departure}

Now, you can run the prompt to get a new itinerary!

现在，您可以运行提示来获取新的行程！

In [31]:
prompt = f"""I will visit {city}, {country}, from {arrival} to {departure}. 
Please create a detailed daily itinerary."""

print_llm_response(prompt)

Here's a realistic, balanced 7-day Rio itinerary (July 9–16), optimized for July’s mild, dry winter weather (15–24°C / 59–75°F), lower crowds, and safety:

**Key Notes First:**
- **Safety:** Stick to tourist zones (Zona Sul, Centro), avoid favelas unless with a *reputable* guided tour (e.g., Favela Bike Tour in Rocinha), use Uber/99 (not street taxis), and avoid displaying valuables.
- **Transport:** Use Metro (Linha 1 & 2) for Centro/Copacabana/Ipanema; Uber for longer trips.
- **Book Ahead:** Christ the Redeemer (timed entry), Sugarloaf cable car, Maracanã tour, and popular restaurants.

---

### **Day 1 (Mon, Jul 9): Arrival & Copacabana Immersion**
- **Afternoon:** Check into hotel (e.g., *Hotel Fasano Rio* or *Copacabana Palace*). Stroll **Copacabana Beach**, watch sunset from **Fortaleza de São João** (free, panoramic views).
- **Evening:** Dinner at **Garota de Ipanema** (iconic bossa nova venue) or casual *churrasco* at **Porcão Rio’s** (Copacabana).

### **Day 2 (Tue, Jul 10): Christ the Redeemer & Santa Teresa**
- **Morning:** **Christ the Redeemer** (book 8:30 AM slot via [rio.gov.br](https://www.rio.gov.br)) — take van from Largo do Machado (cheaper than Corcovado train).
- **Afternoon:** Explore **Santa Teresa**: tram ride, bohemian streets, **Parque das Ruínas**, and **Lapa Arches** (photo op).
- **Evening:** Dinner at **Aprazível** (stunning views, traditional cuisine) or **Bar do Mineiro** (authentic local vibe).

### **Day 3 (Wed, Jul 11): Sugarloaf & Urca Charm**
- **Morning:** **Sugarloaf Mountain** (book 10 AM cable car; go early to avoid lines). Hike or take cable car to **Pão de Açúcar**, then **Morro da Urca**.
- **Afternoon:** Lunch at **Urca’s waterfront cafes**, then walk **Pedra do Arpoador** for sunset (famous photo spot).
- **Evening:** Samba show at **Rio Scenarium** (Lapa) — book tickets ahead.

### **Day 4 (Thu, Jul 12): Tijuca Forest & Botanical Garden**
- **Morning:** **Tijuca National Park**: Jeep tour to **Cascata do Taquara** (waterfall) and **Vista Chinesa** (scenic overlook). Spot monkeys!
- **Afternoon:** **Jardim Botânico** (120+ orchid species, giant Victoria amazonica lilies).
- **Evening:** Casual dinner at **Confeitaria Colombo** (historic café, Centro) — try *pão de queijo*.

### **Day 5 (Fri, Jul 13): Maracanã & Modern Rio**
- **Morning:** **Maracanã Stadium tour** (book ahead; includes museum and pitch access).
- **Afternoon:** **Museu do Amanhã** (Tomorrow’s Museum) + **Museu de Arte do Rio (MAR)** in revitalized **Porto Maravilha**. Walk along **Mauá Pier**.
- **Evening:** Drinks at **Bar Urca** (sunset views) or rooftop bar **Sky Bar** (Copacabana).

### **Day 6 (Sat, Jul 14): Beach Day & Local Culture**
- **Morning:** **Ipanema Beach** — rent a chair (*mesa e cadeira*), try *açaí* at a kiosk, people-watch at **Posto 9**.
- **Afternoon:** **Feira Hippie de Ipanema** (Sat only, 10 AM–6 PM) for crafts, jewelry, and street food.
- **Evening:** Dinner at **Azul Marinho** (seafood, Ipanema) or **Braseiro da Gávea** (classic churrasco).

### **Day 7 (Sun, Jul 15): Day Trip to Niterói or Relaxation**
- **Option A (Culture):** Ferry to **Niterói** → **MAC Museum** (Oscar Niemeyer’s iconic architecture) + **Praia de Piratininga**.
- **Option B (Relax):** Spa day at **Spa Q4** (Copacabana) or beach time.
- **Evening:** Farewell dinner at **Olympe** (Michelin-starred French-Brazilian) or **Chakras** (vegetarian, Ipanema).

### **Day 8 (Mon, Jul 16): Departure**
- Morning: Last-minute souvenir shopping at **Rua Farme de Amoedo** (Ipanema) or **Casa Shopping** (Centro).
- Transfer to GIG Airport (allow 1.5 hrs; Uber ~R$80).

---

### **Essential Tips:**
- **Money:** Use cards widely; carry some cash (R$) for markets/taxis.
- **Health:** Tap water is *not* safe — drink bottled/filtered.
- **Packing:** Light layers (cool mornings), rain jacket (rare but possible), reef-safe sunscreen, comfortable shoes.
- **Apps:** Google Maps (offline), Uber/99, iFood (food delivery), and **RioCard** for Metro/bus.

Enjoy Rio’s energy, rhythm, and beauty — and *bom viagem!* 🇧🇷

### Challenge exercise!

###挑战练习！

Complete the code below so that it will **print out the country of every destination** in the `itinerary.csv` file. Ask the chatbot for help if you need it!

完成下面的代码，以便它在“itinerary.csv”文件中**打印出每个目的地的国家/地区**。如果需要，请向聊天机器人寻求帮助！

In [32]:
f = open("itinerary.csv", "r")
csv_reader = csv.DictReader(f)
itinerary = []
for row in csv_reader:
    print(row)
    itinerary.append(row)
f.close()

# Complete the next two lines to print the country:
for trip_stop in itinerary:
    print(trip_stop["Country"])

{'Arrival': 'July-01', 'Departure': 'July-08', 'City': 'New York', 'Country': 'USA'}
{'Arrival': 'July-09', 'Departure': 'July-16', 'City': 'Rio de Janeiro', 'Country': 'Brazil'}
{'Arrival': 'July-17', 'Departure': 'July-24', 'City': 'Cape Town', 'Country': 'South Africa'}
{'Arrival': 'July-25', 'Departure': 'August-01', 'City': 'Istanbul', 'Country': 'Turkey'}
{'Arrival': 'August-02', 'Departure': 'August-09', 'City': 'Paris', 'Country': 'France'}
{'Arrival': 'August-10', 'Departure': 'August-17', 'City': 'Tokyo', 'Country': 'Japan'}
{'Arrival': 'August-18', 'Departure': 'August-25', 'City': 'Sydney', 'Country': 'Australia'}
USA
Brazil
South Africa
Turkey
France
Japan
Australia