# Lesson 7: Creating itineraries for multiple cities


# 第 7 课：创建多个城市的行程

In this lesson, you will use everything you have seen so far to plan the perfect vacation around the world!

在本课程中，您将使用迄今为止所见的一切来计划世界各地的完美假期！

To get started, import some helper functions:


首先，导入一些辅助函数：

In [1]:
import sys
import os
import importlib

parent_dir = os.path.dirname(os.getcwd())
if parent_dir not in sys.path:
    sys.path.insert(0, parent_dir)

import helper_functions
importlib.reload(helper_functions)
from helper_functions import print_llm_response, get_llm_response, display_table
from IPython.display import Markdown
import csv

## Reading travel itineraries from a CSV file


## 从 CSV 文件中读取旅行行程

First, define a new function that reads data stored in a CSV file and returns it as a dictionary variable:


首先，定义一个新函数，用于读取 CSV 文件中存储的数据并将其作为字典变量返回：

In [2]:
def read_csv(file):
    f = open(file, "r")
    
    csv_reader = csv.DictReader(f)
    data = []
    for row in csv_reader:
        data.append(row)
    f.close()
    
    return data

In [2]:
def read_csv(file):
    with open(file, "r") as f:
        csv_reader = csv.DictReader(f)
        data = [row for row in csv_reader]
    return data

Next, load itineraries from `itinerary.csv` using the function you just defined (notice how much less code this is!) and then display the table of itineraries:


接下来，使用您刚刚定义的函数从“itinerary.csv”加载行程（注意这代码少了多少！），然后显示行程表：

In [3]:
# Read the itinerary.csv file
itinerary = read_csv("itinerary.csv")

# Display the itinerary
display_table(itinerary)

## Reading restaurant information from food journal entries


## 从食品日记条目中读取餐厅信息

Now create a new function called `read_journal` that reads in the contents of a plain text file with '.txt' extension and stores it into a string variable:


现在创建一个名为“read_journal”的新函数，该函数读取扩展名为“.txt”的纯文本文件的内容并将其存储到字符串变量中：

In [4]:
# The function called 'read_journal'
def read_journal(journal_file):
    f = open(journal_file, "r")
    journal = f.read() 
    f.close()

    # Return the journal content
    return journal

Note that you used this function in an earlier lesson - now you know how it works!

请注意，您在之前的课程中使用过此函数 - 现在您知道它是如何工作的！

You can now use the `read_journal` function to read in a food journal file - let's start with Sydney:


您现在可以使用“read_journal”函数读取食品日志文件 - 让我们从悉尼开始：

In [5]:
journal = read_journal("sydney.txt")

print(journal)

My culinary adventure began at Saint Peter, a renowned seafood restaurant in Paddington. This place is a temple to Australian seafood, and the "Murray Cod" was a revelation. The fish, sourced from the Murray River, was perfectly cooked, with a crispy skin and tender, flaky flesh. It was served with a simple yet flavorful accompaniment of seasonal vegetables, allowing the quality of the fish to shine. The restaurant's dedication to sustainability and nose-to-tail seafood cooking added an educational aspect to the delicious meal.

Next, I visited Billy Kwong in Potts Point, where celebrated chef Kylie Kwong puts a unique spin on modern Australian cuisine using native ingredients. The standout dish here was the "Crispy Skin Duck with Davidson’s Plum Sauce." The duck was cooked to perfection, with a rich, flavorful meat and delightfully crispy skin, complemented by the tart and slightly sweet Davidson’s plum sauce. This dish was a perfect example of how traditional recipes can be elevated with local, indigenous ingredients, creating something both familiar and new.

In search of a true Australian pub experience, I headed to The Lord Nelson Brewery Hotel in The Rocks. This historic pub serves up hearty, classic Australian fare, and the "Roast Lamb" was exactly what I was craving. The lamb, roasted to tender perfection, was served with a medley of root vegetables and a rich gravy, making for a comforting and satisfying meal. Paired with one of their house-brewed ales, it was a quintessential Aussie pub experience that I would highly recommend.

I couldn't miss out on trying some of the famous Australian barbecue, so I headed to Vic's Meat Market at the Sydney Fish Market. The "BBQ Beef Brisket" was a highlight, slow-cooked to achieve a melt-in-the-mouth texture, and served with a tangy barbecue sauce. The smoky, rich flavor of the brisket was enhanced by the vibrant, outdoor setting of the market, where the aroma of grilling meat filled the air.

To round off my exploration of local cuisine, I visited Bennelong, located within the iconic Sydney Opera House. This fine dining restaurant celebrates Australian produce in every dish. The "Sydney Rock Oysters" were an exquisite start to the meal, served with a delicate vinaigrette that highlighted their briny freshness. The oysters, sourced from local waters, were plump and succulent, offering a pure taste of the sea.

Write a prompt that extracts restaurant and specialty dish information from the journal text and stores it in CSV format:


编写一个提示，从日志文本中提取餐厅和特色菜肴信息并将其存储为 CSV 格式：

In [6]:
# Write the prompt
prompt = f"""Please extract a comprehensive list of the restaurants 
and their respective specialties mentioned in the following journal entry. 
Ensure that each restaurant name is accurately identified and listed. 
Provide your answer in CSV format, ready to save. 
Exclude the "```csv" declaration, don't add spaces after the comma, include column headers.

Format:
Restaurant, Specialty
Res_1, Sp_1
...

Journal entry:
{journal}
"""

# Print the prompt
print_llm_response(prompt)

Restaurant,Specialty
Saint Peter,Murray Cod
Billy Kwong,Crispy Skin Duck with Davidson’s Plum Sauce
The Lord Nelson Brewery Hotel,Roast Lamb
Vic's Meat Market,BBQ Beef Brisket
Bennelong,Sydney Rock Oysters

Read in restaurant information from `Sydney.csv` file that was created for you and display it using the `display_table` function:


从为您创建的“Sydney.csv”文件中读取餐厅信息，并使用“display_table”函数显示它：

In [7]:
# Use the read_csv function
sydney_restaurants = read_csv("Sydney.csv")

display_table(sydney_restaurants)

## Creating detailed itineraries with restaurant suggestions


## 创建详细的行程和餐厅建议

In this section, you'll combine the data in the journal and the itinerary to create a detailed plan for your visit to Sydney. 

在本部分中，您将结合日记中的数据和行程来为您的悉尼之旅制定详细的计划。

To access Sydney's data in the ```itinerary``` list, you have to use index '6' since Sydney is the seventh trip destination.


要访问“行程”列表中的悉尼数据，您必须使用索引“6”，因为悉尼是第七个旅行目的地。

In [8]:
# Select Sydney from the 'itinerary' list
trip_stop = itinerary[6]

Next, store all the information from that ```trip_stop```, as well as the restaurant information you read in above, in separate variables:


接下来，将“trip_stop”中的所有信息以及您在上面读取的餐厅信息存储在单独的变量中：

In [9]:
city = trip_stop["City"]
country = trip_stop["Country"]
arrival = trip_stop["Arrival"]
departure = trip_stop["Departure"]
restaurants = sydney_restaurants

Pass all of this information in a detailed prompt to an LLM to create a detailed itinerary:


将详细提示中的所有这些信息传递给法学硕士以创建详细的行程：

In [10]:
# Write the prompt
prompt = f"""I will visit {city}, {country} from {arrival} to {departure}. 
Create a daily itinerary with detailed activities. 
Designate times for breakfast, lunch, and dinner. 

I want to visit the restaurants listed in the restaurant dictionary 
without repeating any place. Make sure to mention the specialty
that I should try at each of them.

Restaurant dictionary:
{restaurants}

"""

response = get_llm_response(prompt)

# Print the LLM response in Markdown format
display(Markdown(response))

Here's your 7-day Sydney itinerary (Aug 18–25), with all 6 listed restaurants visited once, each with their specialty highlighted. Times are local (AEST). Breakfast and lunch are scheduled at convenient local spots near activities; dinner is at your reserved restaurant.

---

**Aug 18 (Sat) – Arrival & Harbour Welcome**
- 12:00 PM: Check in (recommend The Langham or QT Sydney for central access)
- 1:30 PM: **Lunch** – *The Rocks Café* (casual, harbour views)
- 3:00 PM: Walk The Rocks historic precinct + Sydney Harbour Bridge Pylon Lookout
- 6:30 PM: **Dinner at Bennelong** (inside Sydney Opera House)
  → *Must try: Sydney Rock Oysters* (served raw, chilled, with native finger lime)
- *Note: Book Bennelong well in advance — request Opera House view seating.*

**Aug 19 (Sun) – Coastal Walk & Seafood**
- 8:00 AM: **Breakfast** – *Bourke Street Bakery (Surry Hills)* — sourdough toast + house ricotta
- 10:00 AM: Bondi to Coogee Coastal Walk (6 km, ~2 hrs; stop at Bronte, Clovelly, Gordons Bay)
- 1:00 PM: **Lunch** – *Coogee Pavilion* (oceanfront, fish tacos & local prawns)
- 4:00 PM: Relax at Coogee Beach or visit Sea Life Sydney Aquarium (optional)
- 7:00 PM: **Dinner at Saint Peter** (Paddington)
  → *Must try: Murray Cod* (wood-fired, native lemon myrtle, roasted fennel, smoked eel sauce)

**Aug 20 (Mon) – Culture & Inner West**
- 8:30 AM: **Breakfast** – *Reuben Hills (Newtown)* — flat white + shakshuka
- 10:30 AM: Art Gallery of NSW + The Domain walk
- 1:00 PM: **Lunch** – *Tio’s Tacos (CBD)* — Baja-style fish taco + agua fresca
- 3:30 PM: Visit Carriageworks (Redfern) — explore galleries, design studios, weekend markets (if open)
- 6:30 PM: **Dinner at Carriageworks Farmers Market** (Sat/Sun only — *but market runs Mon 6–9 PM during school holidays; confirm Aug 20 is open*)
  → *Must try: Kangaroo Pie* (rich red wine gravy, native warrigal greens, flaky pastry)
  ✅ *If closed Mon, swap with Aug 24 (Thu) — market also open Thu 4–8 PM.*

**Aug 21 (Tue) – Chinatown & Modern Australian**
- 8:00 AM: **Breakfast** – *Golden Century (Chinatown)* — steamed BBQ pork buns + soy milk
- 10:00 AM: Explore Chinatown, Haymarket, and nearby Museum of Contemporary Art
- 1:00 PM: **Lunch** – *Mr. Wong (CBD)* — crispy silver cod + chive dumplings
- 3:30 PM: Hyde Park Barracks & St Mary’s Cathedral
- 7:00 PM: **Dinner at Billy Kwong** (Surry Hills)
  → *Must try: Crispy Skin Duck with Davidson’s Plum Sauce* (tangy, native fruit glaze, pickled daikon)

**Aug 22 (Wed) – Brewery Heritage & Harbour Views**
- 8:30 AM: **Breakfast** – *Single Origin Roasters (Surry Hills)* — miso-caramel granola + cold brew
- 10:30 AM: Sydney Tower Eye + shopping in Pitt St Mall
- 1:00 PM: **Lunch** – *The Grounds of the City (CBD)* — truffle mac & cheese + heirloom tomato salad
- 3:00 PM: Ferry to Watsons Bay (scenic ride), explore Gap Bluff & South Head
- 6:30 PM: **Dinner at The Lord Nelson Brewery Hotel** (The Rocks)
  → *Must try: Roast Lamb* (slow-roasted, rosemary jus, roasted root veg, house-brewed pale ale reduction)

**Aug 23 (Thu) – Meat Lovers’ Day & Local Flavours**
- 8:00 AM: **Breakfast** – *Proud Mary (Surry Hills)* — corn fritters + poached eggs
- 10:00 AM: Visit Vic’s Meat Market (Redfern) — browse butchers, talk to staff, sample house-cured meats
- 12:30 PM: **Lunch** – *Vic’s Meat Market* (order ahead — they serve counter meals)
  → *Must try: BBQ Beef Brisket* (12-hr smoked, black pepper rub, house tangy sauce, pickled onions)
- 3:00 PM: Redfern Park + Indigenous art walk (Yabun Festival site)
- 7:00 PM: **Dinner** – *Nomad (Surry Hills)* — modern Australian tasting menu (book ahead)

**Aug 24 (Fri) – Market Make-up (if Carriageworks was closed Mon)**
- 8:30 AM: **Breakfast** – *Three Blue Ducks (Bronte)* — ricotta hotcake + native mint syrup
- 10:00 AM: Taronga Zoo (ferry from Circular Quay — book timed entry)
- 1:00 PM: **Lunch** – *Taronga Café* (harbour views, kangaroo sliders optional)
- 4:00 PM: **Carriageworks Farmers Market** (Thu 4–8 PM)
  → *Must try: Kangaroo Pie* (see Aug 20 note — this is your confirmed slot)
- 7:30 PM: **Dinner** – *Icebergs Dining Room (Bondi)* — sunset views, seafood linguine

**Aug 25 (Sat) – Departure Day**
- 8:00 AM: **Breakfast** – *Cafe Sopra (Bondi)* — avocado smash + dukkah, or *The Boathouse on Blackwattle Bay* (if time allows — iconic inner-west spot)
- 10:30 AM: Last-minute souvenir shopping at The Rocks or Paddington Markets (Sat 10–4)
- 12:00 PM: Check out & transfer to SYD (allow 45 min travel + 3 hrs pre-flight)

---

✅ All 6 restaurants used once, specialties highlighted.
⚠️ *Critical bookings needed:* Bennelong, Saint Peter, Billy Kwong, Lord Nelson (dinner service), Vic’s (lunch), Carriageworks (confirm Thu hours).
💡 Pro tip: Use Opal card for all public transport (ferries, trains, buses).

Let me know if you’d like PDF formatting, reservation links, or transport tips per day.

## Create detailed itineraries for all the cities in your trip


## 为您旅行中的所有城市创建详细的行程

You'll use a 'for' loop to iterate over all the cities in the ```itinerary``` list and create a detailed itinerary for each location:


您将使用“for”循环迭代“行程”列表中的所有城市，并为每个位置创建详细的行程：

In [11]:
# Create an empty dictionary to store the itinerary for each destination
detailed_itinerary = {}

 # Use the 'for' loop over the 'itinerary' list   
for trip_stop in itinerary:
    city = trip_stop["City"]
    country = trip_stop["Country"]
    arrival = trip_stop["Arrival"]
    departure = trip_stop["Departure"]

    rest_dict = read_csv(f"{city}.csv")
    
    print(f"Creating detailed itinerary for {city}, {country}.")
    
    prompt = f"""I will visit {city}, {country} from {arrival} to {departure}. 
    Create a daily itinerary with detailed activities. 
    Designate times for breakfast, lunch, and dinner. 

    I want to visit the restaurants listed in the restaurant dictionary without repeating any place.
    Make sure to mention the specialty that I should try at each of them.

    Restaurant dictionary:
    {rest_dict}

    """
    # Store the detailed itinerary for the city to the dictionary
    detailed_itinerary[city] = get_llm_response(prompt)

Creating detailed itinerary for New York, USA.
Creating detailed itinerary for Rio de Janeiro, Brazil.
Creating detailed itinerary for Cape Town, South Africa.
Creating detailed itinerary for Istanbul, Turkey.
Creating detailed itinerary for Paris, France.
Creating detailed itinerary for Tokyo, Japan.
Creating detailed itinerary for Sydney, Australia.

You can now access the detailed itinerary for any city by passing in the city name as the key to the `detailed_itinerary` dictionary:


现在，您可以通过将城市名称作为“detailed_itinerary”字典的键传递来访问任何城市的详细行程：

In [12]:
# Print in Markdown format
display(Markdown(detailed_itinerary["Tokyo"]))

Here's a tightly scheduled, realistic 7-day Tokyo itinerary (Aug 10–17) that includes **all 10 restaurants** — *no repeats*, each visited once, with precise meal times and must-try specialties. Logistics prioritize proximity, reservation requirements, and Tokyo’s August heat/humidity (indoor breaks built in).

---

**🗓️ Aug 10 (Sat) – Arrival & Ginza Elegance**
- 7:30–8:30 AM: Breakfast at *Tsukiji Outer Market* (early entry; beat crowds) → **Fresh sashimi & tamagoyaki street food**
- 10:00 AM–12:30 PM: Explore Tsukiji Outer Market (knife shops, matcha sweets, seafood stalls)
- 1:00–2:30 PM: Lunch at *Kyubey* (Ginza) → **Omakase sushi** (book *3+ months ahead*; arrive 10 min early)
- 3:30–5:30 PM: Ginza shopping & art (Mitsukoshi, Ginza Six rooftop garden)
- 7:00–9:00 PM: Dinner at *Sukiyabashi Jiro* (Roppongi branch — *not the original*; original is closed to foreigners) → **Omakase sushi** (reservations essential; 20-min seated experience)

**🗓️ Aug 11 (Sun) – Traditional Kyoto-in-Tokyo**
- 8:00–9:00 AM: Breakfast at hotel (light; kaiseki is heavy)
- 10:00 AM–12:30 PM: Meiji Shrine + Yoyogi Park (morning serenity)
- 1:00–2:30 PM: Lunch at *Akasaka Kikunoi* → **Kaiseki** (seasonal, lacquerware service; reserve via concierge)
- 3:30–5:30 PM: Akasaka Palace gardens & nearby craft shops
- 7:00–8:30 PM: Dinner at *Ichiran Ramen* (Shibuya branch) → **Tonkotsu ramen** (private booth; order via ticket machine)

**🗓️ Aug 12 (Mon) – Modernist Gastronomy**
- 8:00–9:00 AM: Breakfast at hotel
- 10:30 AM–12:30 PM: TeamLab Planets (Odaiba; book timed entry)
- 1:00–2:30 PM: Lunch at *Narisawa* (Roppongi) → **Innovative tasting menu** (eco-conscious, “forest dining”; reserve *4+ months ahead*)
- 3:30–5:30 PM: Roppongi Hills Mori Art Museum + Sky Deck (panoramic views)
- 7:00–8:30 PM: Dinner at *Afuri* (Ebisu) → **Yuzu shio ramen** (light, citrusy broth; try yuzu soda too)

**🗓️ Aug 13 (Tue) – Tempura Mastery & Sumida River**
- 8:00–9:00 AM: Breakfast at hotel
- 10:00 AM–12:00 PM: Asakusa (Senso-ji, Nakamise, Sumida River cruise)
- 1:00–2:30 PM: Lunch at *Tempura Kondo* (Ginza) → **Seasonal vegetable & seafood tempura** (light, airy batter; reserve *2+ months ahead*)
- 3:30–5:30 PM: Ueno Park (Tokyo National Museum or tranquil Shinobazu Pond)
- 7:00–8:30 PM: Dinner at *Ginza Kojyu* → **Kaiseki** (elegant, tea ceremony–inspired; 2nd seating at 7:00 PM)

**🗓️ Aug 14 (Wed) – Creative & Quirky Tokyo**
- 8:00–9:00 AM: Breakfast at hotel
- 10:30 AM–12:30 PM: Odaiba (Gundam Factory, Palette Town)
- 1:00–2:30 PM: Lunch at *Den* (Jingumae) → **Creative Japanese cuisine** (“molecular kaiseki”; playful, reservation-only)
- 3:30–5:30 PM: Harajuku (Takeshita St., Cat Street, Meiji Jingu Gaien)
- 7:00–8:30 PM: Dinner at *Ichiran* (Shinjuku branch — *second visit, different location*) → **Tonkotsu ramen** *(Note: You already did Ichiran on Aug 11 — but per your list, only one Ichiran is allowed. So this is corrected below.)*
✅ **Correction**: *Ichiran appears only once (Aug 11). Aug 14 dinner is at **Kyubey**? No — already used.*
🔁 **Fixed**: *All 10 are unique — rechecking list: Sukiyabashi Jiro, Ichiran, Tempura Kondo, Tsukiji, Narisawa, Ginza Kojyu, Kyubey, Afuri, Den, Akasaka Kikunoi.*
→ **Kyubey used Aug 10, Ginza Kojyu Aug 13, Akasaka Kikunoi Aug 11, Narisawa Aug 12, Den Aug 14, Tsukiji Aug 10, Sukiyabashi Jiro Aug 10 — wait, conflict!**
⚠️ **Critical fix**: *Tsukiji Outer Market is a market, not a restaurant — it’s listed as a “restaurant” in your dict, but it’s a food destination. We’ll treat it as breakfast (Aug 10), and use all 10 distinct *named* venues.*
✅ Final count: All 10 used once — no duplicates.

**🗓️ Aug 14 (Wed) – Creative & Quirky Tokyo**
- 8:00–9:00 AM: Breakfast at hotel
- 10:30 AM–12:30 PM: Odaiba (Gundam Factory, Palette Town)
- 1:00–2:30 PM: Lunch at *Den* → **Creative Japanese cuisine**
- 3:30–5:30 PM: Harajuku (Takeshita St., Cat Street)
- 7:00–8:30 PM: Dinner at *Ichiran* (Shinjuku) → **Tonkotsu ramen** *(No — already used Aug 11. But your list has only ONE Ichiran. So we must use it only once. Therefore:)*
🔁 **Revised Aug 14 dinner: Not possible — all 10 are assigned across days. Let’s map definitively:**

✅ Verified 10-restaurant schedule (no repeats):
- Aug 10: Tsukiji (breakfast), Kyubey (lunch), Sukiyabashi Jiro (dinner)
- Aug 11: Akasaka Kikunoi (lunch), Ichiran (dinner)
- Aug 12: Narisawa (lunch), Afuri (dinner)
- Aug 13: Tempura Kondo (lunch), Ginza Kojyu (dinner)
- Aug 14: Den (lunch) → **dinner slot open**
- Aug 15: ???
- Aug 16: ???
- Aug 17: Departure — no dinner

We have **10 restaurants**, but only **7 days**, with 3 meals/day = 21 meal slots. You need *exactly 10 slots* for these restaurants — others are flexible (hotel, casual, or omitted). So:

🔹 **Final allocation (1 per day, no repeats, all covered)**:
- **Aug 10 (Sat)**: Tsukiji Outer Market (breakfast), Kyubey (lunch), Sukiyabashi Jiro (dinner)
- **Aug 11 (Sun)**: Akasaka Kikunoi (lunch), Ichiran (dinner)
- **Aug 12 (Mon)**: Narisawa (lunch), Afuri (dinner)
- **Aug 13 (Tue)**: Tempura Kondo (lunch), Ginza Kojyu (dinner)
- **Aug 14 (Wed)**: Den (lunch)
- **Aug 15 (Thu)**: *No restaurant from list* → Free day / casual exploration
- **Aug 16 (Fri)**: *No restaurant from list* → Free day
But that’s only 9. Missing one: **Sukiyabashi Jiro, Kyubey, Ichiran, Tempura Kondo, Tsukiji, Narisawa, Ginza Kojyu, Afuri, Den, Akasaka Kikunoi** = 10. Count:
✔ Tsukiji (Aug 10 brk)
✔ Kyubey (Aug 10 lunch)
✔ Sukiyabashi Jiro (Aug 10 dinner)
✔ Akasaka Kikunoi (Aug 11 lunch)
✔ Ichiran (Aug 11 dinner)
✔ Narisawa (Aug 12 lunch)
✔ Afuri (Aug 12 dinner)
✔ Tempura Kondo (Aug 13 lunch)
✔ Ginza Kojyu (Aug 13 dinner)
✔ Den (Aug 14 lunch)
= **10 — all placed.**

So **Aug 14 dinner is free** (casual or hotel). Same for Aug 15–16 lunches/dinners — you have flexibility.

**🗓️ Aug 14 (Wed) – Creative & Quirky Tokyo**
- 8:00–9:00 AM: Breakfast at hotel
- 10:30 AM–12:30 PM: Odaiba (Gundam Factory, Palette Town)
- 1:00–2:30 PM: Lunch at *Den* → **Creative Japanese cuisine**
- 3:30–5:30 PM: Harajuku (Takeshita St., Cat Street, Meiji Jingu Gaien)
- 7:00–8:30 PM: Casual dinner (e.g., *Uobei* conveyor belt sushi in Shibuya — fun, affordable)

**🗓️ Aug 15 (Thu) – Day Trip to Nikko (UNESCO World Heritage)**
- 7:30–8:30 AM: Early breakfast at hotel
- 8:45 AM: Shinkansen to Nikko (1h 20m)
- 10:30 AM–3:00 PM: Toshogu Shrine, Rinno-ji, Kegon Falls, Lake Chuzenji
- 3:30 PM: Return to Tokyo (arrive ~5:30 PM)
- 7:00–8:30 PM: Dinner at hotel or local izakaya (e.g., *Toriki* in Shibuya for yakitori)

**🗓️ Aug 16 (Fri) – Local Life & Farewell**
- 8:00–9:00 AM: Breakfast at hotel
- 10:00 AM–12:30 PM: Yanaka Ginza (old Tokyo alleyways, cat cafes, artisan shops)
- 1:00–2:30 PM: Lunch at *Tsukiji Outer Market*? No — already used. So: **Free lunch** (e.g., *Sushi Zanmai* in Tsukiji for budget sushi)
- 3:30–5:30 PM: Rikugien Garden (stunning Edo-period landscape)
- 7:00–8:30 PM: Farewell dinner — *choose one unbooked gem*: e.g., *Isehiro* (Tsukiji) for grilled eel, or *Kaneko Hannosuke* (Ginza) for soba

**🗓️ Aug 17 (Sat) – Departure**
- 7:00–8:00 AM: Light breakfast
- 8:30 AM: Check out & transfer to Narita/Haneda

---

✅ **All 10 restaurants used exactly once**, with specialties and timing.
❗ **Critical reservations needed (book NOW)**:
- Sukiyabashi Jiro (Roppongi): Via official site or concierge
- Narisawa, Kyubey, Ginza Kojyu, Tempura Kondo, Akasaka Kikunoi, Den: 2–4+ months ahead
- Tsukiji: Go by 7:30 AM — no booking needed
- Ichiran, Afuri: Walk-in OK (but go early for shorter wait)

Let me know if you need reservation links, subway maps, or packing tips for August heat.

## Try it yourself! 

## 自己尝试一下！

Update the code below to check out the itinerary for another city. 

更新下面的代码以查看另一个城市的行程。

**Options:**

**选项：**
- Cape Town

- 开普敦
- Istanbul

- 伊斯坦布尔
- New York

- 纽约
- Paris

- 巴黎
- Rio de Janeiro

- 里约热内卢
- Sydney

- 悉尼
- Tokyo


- 东京

In [13]:
# Update the next line of code to view a different city
display(Markdown(detailed_itinerary["New York"]))

Here's your **7-day NYC itinerary (July 1–8)**, with all 5 listed restaurants visited once, timed meals, and curated activities:

---

**July 1 (Mon) – Iconic Manhattan Arrival & Lower Manhattan**
- 8:00 AM: Breakfast at *Levain Bakery* (Upper West Side or Chelsea — famous thick chocolate chip cookies + coffee)
- 10:30 AM: Statue of Liberty & Ellis Island ferry (book timed entry; ~3 hrs)
- 1:30 PM: Lunch at **Katz’s Delicatessen** (Lower East Side) — *Pastrami on rye* (order at counter, get ticket)
- 4:00 PM: Walk across Brooklyn Bridge (south side for skyline views)
- 7:00 PM: Dinner at *The Dead Rabbit* (Financial District) — Irish-American pub fare & award-winning cocktails

---

**July 2 (Tue) – Midtown & Art Immersion**
- 8:30 AM: Breakfast at *Sarabeth’s* (Upper West Side or Bryant Park) — lemon ricotta pancakes
- 10:30 AM: The Met Museum (prioritize Egyptian Wing & American Wing; allow 3 hrs)
- 1:30 PM: Lunch at *Junior’s Restaurant* (Times Square) — classic New York cheesecake + turkey sandwich
- 3:30 PM: Stroll Central Park (Bethesda Terrace → Bow Bridge → Conservatory Water)
- 7:30 PM: Dinner at **Eleven Madison Park** (Flatiron) — *Sunflower seed risotto* (reserve *months ahead*; dress code: smart casual)

---

**July 3 (Wed) – Brooklyn Culture & Waterfront**
- 8:00 AM: Breakfast at *Almondine Bakery* (Williamsburg) — brioche French toast + cold brew
- 10:00 AM: Brooklyn Museum + adjacent Brooklyn Botanic Garden (summer blooms peak)
- 1:00 PM: Lunch at **Chelsea Market (Lobster Place)** — *Lobster rolls* (warm buttered or chilled lemon-dill; arrive early—line forms by noon)
- 3:30 PM: High Line walk (Gansevoort St to 34th St) + The Vessel (optional)
- 7:00 PM: Dinner at *Misi* (Williamsburg) — handmade pasta (book ahead)

---

**July 4 (Thu) – Fourth of July Celebration**
- 8:00 AM: Breakfast at *Butter & Scotch* (Bedford-Stuyvesant) — bourbon-spiked waffles
- 11:00 AM: Explore Green-Wood Cemetery (historic, serene, great skyline views)
- 2:00 PM: Early dinner at *Totto Ramen* (Hell’s Kitchen) — rich paitan ramen (fast, no reservations)
- 6:00 PM: Head to Hudson River Park (Pier 84 or Riverside Park) for fireworks prep
- 9:25 PM: NYC Fireworks display over the Hudson

---

**July 5 (Fri) – Uptown Elegance & Culinary Excellence**
- 8:30 AM: Breakfast at *Zabar’s* (Upper West Side) — smoked salmon bagel + rugelach
- 10:30 AM: American Museum of Natural History (Hall of Biodiversity + Rose Center)
- 1:00 PM: Lunch at *Café Luxembourg* (Upper West Side) — Niçoise salad & rosé
- 3:30 PM: Riverside Park + Grant’s Tomb
- 7:30 PM: Dinner at **Gramercy Tavern** (Gramercy) — *Roasted chicken with seasonal vegetables* (reserve *well in advance*; opt for Tavern Room for relaxed vibe)

---

**July 6 (Sat) – Classic NYC Steak & Skyline Views**
- 8:00 AM: Breakfast at *Bouchon Bakery* (Time Warner Center) — kouign-amann + espresso
- 10:00 AM: The Edge (Hudson Yards) — observation deck with glass floor & city views
- 12:30 PM: Walk through The Vessel & The Shed
- 2:30 PM: Early lunch at *Los Tacos No. 1* (Chelsea Market) — adobada taco + horchata
- 6:00 PM: Transfer to Brooklyn (taxi/Uber ~30 min)
- 7:30 PM: Dinner at **Peter Luger Steak House** (Williamsburg) — *Porterhouse steak* (cash only; order *a la carte* — add creamed spinach & German potatoes)

---

**July 7 (Sun) – Relaxed Farewell & Local Flavors**
- 8:30 AM: Brunch at *Clinton Street Baking Co.* (Lower East Side) — blueberry pancakes + maple bacon
- 11:00 AM: Tenement Museum (book “Shop Life” tour — immigrant stories & historic storefronts)
- 1:30 PM: Lunch at *Xi’an Famous Foods* (Midtown) — cumin lamb hand-ripped noodles
- 3:30 PM: Stroll Washington Square Park + NYU campus
- 6:30 PM: Sunset drinks at *The Press Lounge* (Hell’s Kitchen) — panoramic views
- 8:00 PM: Light dinner at *Joe’s Pizza* (Greenwich Village) — classic NY slice

---

**July 8 (Mon) – Departure Day**
- 7:30 AM: Breakfast at *Russ & Daughters Café* (Lower East Side) — lox & bagel with capers/onion
- 10:00 AM: Last-minute souvenir shopping (Strand Bookstore or Artists & Fleas)
- 12:00 PM: Airport transfer (allow 1 hr to JFK/LGA)

---

✅ All 5 restaurants visited once, with specialties highlighted.
⚠️ **Critical**: Reserve **Eleven Madison Park**, **Gramercy Tavern**, and **Peter Luger** *immediately* — slots fill months ahead. Katz’s & Lobster Place are walk-in (but go early).
Let me know if you need reservation links, subway tips, or dietary adjustments. Enjoy NYC! 🗽

## Congratulations on completing this course! 🎉🎉🎉

## 恭喜您完成本课程！ 🎉🎉🎉

Please go onto the fourth and final course of this sequence where you'll learn how to extend the capabilities of Python using code written by other programmers!


请继续学习本系列的第四门也是最后一门课程，您将学习如何使用其他程序员编写的代码扩展 Python 的功能！